-- Normalise the vato uniqueness rule. An earlier revision created a PARTIAL
-- unique index (WHERE reference <> ''), which ON CONFLICT cannot infer, so both
-- this seed and the admin import would fail. Replace it with a plain unique
-- index and represent "no citation" as NULL. Safe to run either way.
ALTER TABLE public.vato ALTER COLUMN reference DROP NOT NULL;
ALTER TABLE public.vato ALTER COLUMN reference DROP DEFAULT;
UPDATE public.vato SET reference = NULL WHERE reference = '';
DROP INDEX IF EXISTS public.vato_reference_key;
CREATE UNIQUE INDEX vato_reference_key ON public.vato(reference);

-- Swamini Vato 1/1 - 1/50, English translation.
--
-- Transcribed from the BAPS published translation supplied by the app owner.
-- Superscript footnote markers are stripped and footnote bodies omitted, so
-- each row holds the passage exactly as published. No text is paraphrased.
--
-- ON CONFLICT keeps this re-runnable and preserves any edit made through the
-- admin screen: an existing reference is left untouched.

INSERT INTO public.vato (text, reference, position) VALUES
  ('One should continuously engage in delivering and listening to talks on the glory of God and his Sadhu. Maharaj has come here (to earth) with his Akshardham, pārshads and all his powers. He is exactly the same (today). He whom we wish to attain after death, we have attained during this life; there is nothing more left to attain. If this truth is not understood properly, the jiva remains weak. Once this is understood, the jiva will no longer consider itself weak and will acquire a different mettle. Also, there is no greater endeavour than to understand the glory of God. Without understanding the glory, even countless other endeavours will not enable the jiva to attain spiritual strength. The means to understanding this glory is profound association with such a holy Sadhu, and without it the true glory of God cannot be understood.', 'Glory of God (37.1) / (1/1)', 1),
  ('Without learning the teachings of Sānkhya, faults such as greed, lust, taste, attachment and ego, and the three miseries – due to adhyātma, adhibhut and adhidaiv – cannot be removed. Without Sānkhya, satsang is said to be only half complete. Thus, to remain happy learn the principles of Sānkhya.', 'Happiness (1.1) / (1/2)', 2),
  ('Prahladji fought for many days with Narayan, but God was not won over. Then God told Prahlad, “I cannot be won over by such wars. The way to win me over is by singing my bhajans, thinking of me in your mind and cherishing my murti in your eyes. In this way, always remember me.” Then, Prahlad tried this method and God was won over within six months. Thus, to please God, learn this method, which is the best.', 'To Please God and His Holy Sadhu (34.1) / (1/3)', 3),
  ('If one has from within (essentially and earnestly) understood the glory of God, then whatever difficult circumstances arise or whatever ill health arises, one still believes, “Without God’s wish nobody can move even a leaf.” With this understanding, one remains happy. And if one does not understand this and encounters difficult circumstances, then his satsang will be spoiled.', 'Glory of God (37.2) / (1/4)', 4),
  ('What spiritual endeavours will this jiva undertake? Attaining moksha through spiritual means can be likened to farming with the aid of bullocks and a labourer to irrigate the field by drawing water from a well. It requires a great deal of effort. The little crop that is raised is eaten by cattle and birds. Attaining moksha through the grace of God is like raising a crop when the rainfall is plentiful. Then, even if the cattle and birds eat it or thieves steal it, the crop will never get exhausted. Wells, lakes and rivers may dry, but not oceans. Similarly, liberation through God is like that. This is extremely rare, but its glory is not understood.', 'Moksha (48.1) / (1/5)', 5),
  ('If one has served the great Sadhu and acquired his virtues then adverse circumstances will have no effect on one. This is like the darkness which disappears in the presence of the Sun, but is unable to exist there.', 'Glory of the Sadhu (30.1) / (1/6)', 6),
  ('One should attach one’s jiva to a sadhu who is attached to God, obeys God’s commands and knows God’s wishes. From such a sadhu one can acquire all the virtues of dharma, spiritual knowledge, detachment, devotion and upāsanā along with the knowledge of God’s glory. Apart from him, where else can they be acquired? A person acquires the virtues of the sadhu he serves; even if he is a genuine spiritual aspirant if he is not attached to a God-realized Sadhu, he may regress; and even an evil person may progress if he associates with a genuine Sadhu. Thus, the cause of everything is the company of a great Sadhu.', 'Glory of the Sadhu (30.2) / (1/7)', 7),
  ('One who is controlled by his senses can be suppressed, but one who is controlled by his ātmā is not. The former is suppressed by serving him or giving him things. But why should the latter be suppressed? For, he does not desire anything. And he can control countless others but he himself is not controlled.', 'Glory of the Sadhu (30.3) / (1/8)', 8),
  ('One who renounces worldly life and becomes a renunciant overcomes all miseries and becomes happy. But even after becoming a renunciant, the misery associated with base instincts – greed, lust, taste, attachments and ego – remains. As these base instincts are (gradually) overcome, one becomes happier.', 'Base Instincts-Worldly Desires-Drawbacks-Sin (5.1) / (1/9)', 9),
  ('The senses and inner faculties are all bad company. Since, they become engrossed in the sense pleasures they come into contact with. That is also the nature of the jiva. Such a jiva is given all the virtues of dharma, spiritual knowledge, detachment, devotion, glory of God and upāsanā by God’s holy Sadhu.', 'Glory of the Sadhu (30.4) / (1/10)', 10),
  ('Even a satsangi who gets a beautiful wife, plentiful wealth and a good house is said to be in the grip of māyā. Since, a jiva cannot escape from there. Thus, it is good if one attains ordinary things.', 'Maya (6.1) / (1/11)', 11),
  ('When faults (e.g. greed, anger, etc.) remain and are not overcome, does it mean they are merely faults or is there some virtue even in them? That is the question. The answer, “Faults hurt, so one remains meek and humble in Satsang, one retains a need for Satsang and one prays to God. And if one experiences difficulty due to faults, knowledge develops. Without it, such a need does not arise. Therefore, this is a virtue (in a fault).”', 'Base Instincts-Worldly Desires-Drawbacks-Sin (5.2) / (1/12)', 12),
  ('One who does things with his body and offers devotion to God with the understanding that his true form is different from the body (i.e. ātmā) progresses a lot. But if he becomes one with his actions, that is not proper.', 'Atmanishtha-Brahmarup (29.1) / (1/13)', 13),
  ('Even by spoiling ten million tasks, improve your moksha. In case ten million tasks are improved, but moksha is spoilt, what is achieved?', 'Social Dealings and Activities (12.1) / (1/14)', 14),
  ('The jiva is certainly purified through the nine forms of devotion and other endeavours, but not to the extent it is purified by the talks of God’s holy Sadhu. There is nothing as powerful as the words of the Satpurush.', 'Spiritual Discourses and Discussions (17.1) / (1/15)', 15),
  ('Shivji became infatuated with the form of Mohini and lost his senses. Then, he introspected and thought, what is surprising about becoming infatuated with my God’s māyā? He thought this way and felt peace in his heart. Therefore, one may be affected by unfavorable place, time, etc.; but with gnān, one can relieve their misery.', '(1/16)', 16),
  ('God has said, “I am not as pleased by austerities, sacrifices, yoga, observance of vows, donations and other endeavours as I am by satsang.” What is that satsang? “To fold one’s hands before the great God-realized Sadhu and to do as he says.”', 'Satsang (18.1) / (1/17)', 17),
  ('The jiva is very powerful. When it is in the body of a lion, how much strength does it have? But when in the body of a sheep, the same jiva becomes meek.', 'The Jiva (28.1) / (1/18)', 18),
  ('Even by spending tens of millions of rupees, such a sadhu is unattainable. Even by giving tens of millions of rupees, such spiritual talks are unattainable. Even by giving tens of millions of rupees, this human body cannot be attained. And we, too, have taken tens of millions of births. But never have we had such company of the God-realized Sadhu. Otherwise why would we have to take birth?', 'Glory of Attainment (32.1) / (1/19)', 19),
  ('Only God and his holy Sadhu can grant moksha. Detachment cultivates enmity towards material pleasures but does not do the job of God; ātmā-realization breaks attachment from everything but does not do the job of God; and by dharma one remains happy but it also does not do the job of God. Thus, only God and his holy Sadhu give moksha. Therefore, do not find faults in them.', 'Glory of the Sadhu (30.5) / (1/20)', 20),
  ('God has suppressed everyone’s powers; otherwise, one would curse someone and burn them, or become mad and go elsewhere, or end their life on their own. But God does not let that happen.', '(1/21)', 21),
  ('God is ever ready to protect his devotees. How? Just as eyelids protect the eyes, hands protect the neck, a mother protects her child and a king protects his subjects, God protects us.', 'Refuge in God (24.1) / (1/22)', 22),
  ('God gives wealth to some and not to others. How should this be understood? That is the question. The answer, “With excessive wealth, one indulges more in worldly enjoyment (and needless expenditure). Thus, it is proper that one gets less.”', 'Wealth (3.1) / (1/23)', 23),
  ('We will also have to redeem one who, knowingly or unknowingly, says ‘Swaminarayan, Swaminarayan’ five to ten times. And we want to extend satsang throughout the universe.', 'Glory of the Swaminarayan Mahamantra (49.1) / (1/24)', 24),
  ('Whatever happiness exists in māyā is not without misery. This, too, should be kept in mind.', 'Social Dealings and Activities (12.2) / (1/25)', 25),
  ('Much greater than the enjoyment of material pleasures is the bliss of the ātmā and even better is the bliss of God, which is like the chintāmani.', 'Grandeur of God (38.1) / (1/26)', 26),
  ('A person bought wisdom for 100,000 rupees. Similarly, wisdom of the many ways for moksha can be learnt from the God-realized Sadhu.', 'Glory of the Sadhu (30.6) / (1/27)', 27),
  ('It is said that a diamond cannot be cut in any way, except by using the blood of a bed bug. Similarly, desires cannot be destroyed in any way except by doing what the great (Sadhu) instructs, imbibing his virtues and admiring his actions. Otherwise, how great were the endeavours of Saubhari and others? Yet, their desires were not overcome.', 'Base Instincts-Worldly Desires-Drawbacks-Sin (5.3) / (1/28)', 28),
  ('One can attain Satsang, but without close association, there is no happiness. How? It is like a person having food, but without actually eating there is no happiness. Also, one may have clothes but without wearing them there is no happiness. Similarly, without the association of the great Sadhu, one does not get the bliss of Satsang.', 'Satsang (18.2) / (1/29)', 29),
  ('Remembering this Sadhu in the mind destroys the sins of the mind; listening to his talks destroys the sins of the ears; and engaging in his darshan destroys the sins of the eyes. Understand his glory in this way.', 'Glory of the Sadhu (30.7) / (1/30)', 30),
  ('Satsang will grow ten million-fold and there will be ten million times more mandirs, but these talks and discourses will not be attained again and administrative duties will predominate. Therefore, only do that which comes naturally. These workshops (for building mandirs, pilgrim resthouses, etc.) will continue as long as the universe remains. So, cultivate the practice of listening to and giving spiritual discourses. We should aspire for all four spiritual endeavours – dharma, spiritual wisdom, detachment and bhakti – and not keep just one as predominant.', 'Spiritual Discourses and Discussions (17.2) / (1/31)', 31),
  ('After talking on renunciation, detachment, observance of rules and dharma, Swami said, “What is one to do with renunciation and detachment? Whatever the type of jiva, only one who has profound association with the enlightened Sadhu of God is a satsangi. Without this, what is the use even if one offers much devotion? And so what even if he can, through grace, continuously see the murti? Only profound association with the enlightened Sadhu of God is satsang. This satsang is attained by continuously practicing it until the very end of the entire universe. Then, he will not be affected by adverse circumstances. So, do such satsang.”', 'Profound Association-Love-Devotion-Friendship (19.1) / (1/32)', 32),
  ('One can become brahmarup through these talks. Then there will be an equal attitude towards young and old women, dust and gold – and one will not even like to look at these. You may say, “We listen to these talks, yet why does this not happen to us?” But if you plant a mango sapling today, how can mangoes grow by tomorrow? But ten years later that mango tree will give mangoes. This is what happens.', 'Spiritual Discourses and Discussions (17.3) / (1/33)', 33),
  ('We should think, “What is the benefit of getting 100 rupees or 100,000 rupees or 10 million rupees? Since we cannot eat more than a limited amount of food. Think thus and learn to step back from indulgence.”', 'Wealth (3.2) / (1/34)', 34),
  ('“After pondering over all the scriptures, I have distilled one thought from them: God is worthy of our devotion.” In this shlok, Vyasji has revealed the essence of all the scriptures: “Take refuge in God. Similarly, I have found that the essence of everything is close association with a Sadhu.”', 'Satsang (18.3) / (1/35)', 35),
  ('Among all, Lakshmiji’s understanding is superior, because she perceived God as without faults. However, she still considered herself as a woman. Therefore, Uddhavji’s understanding is greater because he was wise (gnāni) and perceived God as innocent. However, he had difficulty leaving his home. Ultimately, Jadbharat’s and Shukji’s understanding is the best because they are aloof of the distinction of male and female.', '(1/36)', 36),
  ('Even if one sits in front of God and looks at him for one kalp, one will not become detached from the vishays without falsifying them. If one attains the company of the Sadhu, then he can detach one from the vishays. Even the experience of nirvikalp samādhi will not cause one to detach from them. However, if one attains the gnān samādhi, then one can detach from the vishays.', '(1/37)', 37),
  ('The strife due to māyā in the form of the inner faculties is very burdensome. See, Bharatji had such detachment and renounced his kingdom, yet he encountered difficulties. How great were Saubhari, Parashar and others. Yet, even they suffered. Thus, a Sadhu gives spiritual knowledge and (a new) life. When he prohibits indulgence in material pleasures, strife is resolved, but not otherwise. Even if one lives a whole lifetime with God, without spiritual knowledge, faults are not overcome.', 'Spiritual Wisdom-Understanding-Ignorance (26.1) / (1/38)', 38),
  ('After reading the Vachanamrut, Swami spoke, “Even if one becomes united with the murti of God (in samādhi), how much clarity of understanding will one have? So, understanding is superior to all, whether or not one can control one’s pulse by yogic powers. And even greater than Sānkhya and Yoga is to understand God as supreme.”', 'Supreme God (42.1) / (1/39)', 39),
  ('Maharaj had said, “Once in Alaiya village, countless jivas were sent to Badrikashram by my grace, but none remained there (due to lack of spiritual knowledge).” Thus, that which is achieved through spiritual wisdom is not possible through grace.', 'Spiritual Wisdom-Understanding-Ignorance (26.2) / (1/40)', 40),
  ('The devotion of one who is affectionate is (shallow) like water in a tank, while the devotion of one who is spiritually wise is (deep) like the water of an artesian well. God and his Sadhu have to look after the affectionate (to keep them in Satsang), but not the spiritually wise.', 'Spiritual Wisdom-Understanding-Ignorance (26.3) / (1/41)', 41),
  ('Some overcome greed, some taste, some attachment, some ego but the desire for women remains in the heart. There is nothing as powerful as beauty and this carnal desire resides in all jivas. It is overcome only with the blessings of the great Sadhu, otherwise it is not.', 'Material Pleasures-Desires-Addictions (8.1) / (1/42)', 42),
  ('I have analysed and found that the jiva has never walked the path of God. This is a totally new venture for it. All jivas constantly think only of eating, women and wealth. This is all they think about, talk about, sing about, discuss and meditate on. And wealth is peculiar only to the human race. But eating and females are desired by all species, since God has set the wheel of māyā in motion. But one who does not desire this is a god of the gods, he is not human. And for eating, women and sleeping, one does not need a teacher. Rivers flow towards the ocean. Similarly, the jiva is inclined towards enjoying the sense pleasures. To turn back from this is the path of a sadhu.', 'Material Pleasures-Desires-Addictions (8.2) / (1/43)', 43),
  ('Even if we want to become attached to this body and this world, God will not allow us to. Just as Ravji Suthar was allowed to marry but not allowed to enjoy marital life. And then his ties with worldly life were broken and he became a sadhu. Similarly, God will not allow us to become bound to worldly ties.', 'Grandeur of God (38.2) / (1/44)', 44),
  ('The body is subject to illness and other miseries. They are overcome when God cures them. No one else can do so. Just as one responds to a soldier carrying the king’s orders, but not to an ordinary man of the village.', 'God is the All-doer (41.1) / (1/45)', 45),
  ('Material pleasures are condemned in Akshardham, Shvetdwip, Badrikashram and in the presence of a great God-realized Sadhu in this world. Apart from these four places, everywhere else, material pleasures are respected.', 'Material Pleasures-Desires-Addictions (8.3) / (1/46)', 46),
  ('God’s abode is Gunatit, i.e. above all material qualities. And we want to make all jivas gunātit. We have heard this spiritual knowledge, which is not possible to get anywhere else, and we will be unable to stay elsewhere. And he whom we have attained is not likely to let us go elsewhere, since he knows how (to keep us with him). And those who listen to today’s knowledge and go to his abode are not tempted by Shvetdwip and anything below it. This spiritual knowledge is like the Portuguese canons. Compared to it other knowledge is just like a firecracker.', 'Spiritual Wisdom-Understanding-Ignorance (26.4) / (1/47)', 47),
  ('The muktas of Badrikashram and Shvetdwip have the strength of renunciation and separation (from the vishays). The muktas of Golok and Vaikunth primarily have love (toward God). The muktas of Akshardham are brahmarup.', '(1/48)', 48),
  ('For a devotee of God, attaining pleasures of the senses is itself narak. It has been said: “Kuntājī dukh māng ke līno, ehi bhakta kī rīti ve; Viṣhay ānand na lahe supan me, jāhi Prabhupad prīti ve.” That is the characteristic of a devotee.', '(1/49)', 49),
  ('When we set aside all work and become free to listen to these spiritual discourses, understand that we are doing tens of millions of tasks. What are they? Through these tasks one’s destiny for hell and rebirth is obliterated. But do not think we are sitting idly.', 'Spiritual Discourses and Discussions (17.4) / (1/50)', 50)
ON CONFLICT (reference) DO NOTHING;
